### ISSUE TITLE
GPG

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Clipboard#1]
> GPG signatures, on the other hand, rely on a different path for verification of the key trust, and thus are useful even if both image and signature come from an unreliable source.

@MichaelTunnell & followers

I have the .iso and the .sig in the same folder. I know where's the Ubuntu keyserver but other than that I'm clueless. I've checksummed the images (and the re-imaged install disk too :)) and everything is fine BUT I want GPG as well.

Could you give me some guidance, please? Much appreciated in advance.

**Comment by MichaelTunnell** [comment]
completely flawed question . . . you have an iso? that's nice, of what? Details are important. :)

**Comment by cinnamoner** [comment]
@MichaelTunnell 
neon-useredition-20170518-1018-amd64  
neon-userltsedition-20170517-0019-amd64

Got 2 actually.

**Comment by cinnamoner** [comment]
Yeah, sure, I'm on Linux. Don't use Windows no more me.

**Comment by cinnamoner** [comment]
But the GPG thing is the issue at hand. I've gotta know.

**Comment by cinnamoner** [comment]
I'd rather use the terminal, if possible.

**Comment by cinnamoner** [comment]
I'm really angry now. Just expressing my feelings.

**Comment by cinnamoner** [comment]
Trust is a matter of choice. Has nothing to do with objective reality.

**Comment by cinnamoner** [comment]
I'd rather use the terminal.

**Comment by cinnamoner** [comment]
@MichaelTunnell When and if you have a little time, please tell me whether you run GPG checks at all. Neither is that method bullet proof. At some moment, one has to trust something.

**Comment by cinnamoner** [comment]
Anyways, I would much appreciate if you could help me out on this GPG thing. As in how exactly should I proceed. Thanks.

**Comment by MichaelTunnell** [comment]
I dont bother with gpg checks in most cases because I rarely download outside of the repo so with repo plus md5 that's pretty much enough for me.

**Comment by cinnamoner** [comment]
> I dont bother with gpg checks in most cases because I rarely download outside of the repo so with repo plus md5 that's pretty much enough for me.

@MichaelTunnell Thanks. That's a reasonable answer.
