### ISSUE TITLE
Telegram vs Wire

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Clipboard#2]
I'm not an open-source purist but I pretty much like what Richard Stallman preaches. It should be that way but for now, at least some of it, remains a desiderata. With that being said, I'm addressing a question. It goes like this: *Which app would he use?*

a) Telegram
b) Wire

Note: *He would probably not use either a or b. However, let's assume (as a purely academic exercise) he (due to whatever extreme situation) must absolutely pick one out of those two apps.*

**Comment by cinnamoner** [comment]
For your convenience, I'm posting some links shortly. Then I shall @ you.

**Comment by cinnamoner** [comment]
https://github.com/telegramdesktop/tdesktop

**Comment by cinnamoner** [comment]
https://github.com/wireapp/wire-desktop

**Comment by cinnamoner** [comment]
https://github.com/telegramdesktop/tdesktop
https://desktop.telegram.org/
***
https://github.com/wireapp/wire-desktop
https://wire.com/download/

Note: *You should check the hompages thoroughly. Otherwise, it's a futile endeavour.*

**Comment by cinnamoner** [comment]
Patience ... I'm not done.

**Comment by cinnamoner** [comment]
Current Telegram 64 bit Linux
File name: tsetup.1.0.14.tar.xz

First half of the SHA256 string: 88dcffe9fe21855dbf335ad6b94d5a99

**Comment by cinnamoner** [comment]
Current Wire 64 bit Linux
File name: wire_2.11.2685_amd64.deb

First half of the SHA256 string: c7cf11f32d829a055402b6611e05645f

**Comment by cinnamoner** [comment]
So, in a nutshell, a SHA256 string has 64 characters in total. I've posted the first half. Please post the second half. Try making use of at least 2 different methods to checksum the files. Then we shall know with reasonable certainty the correct checksums. Should you be interested, of course.

Note: *Do not edit your post(s). The reason is obvious. At least I think so :)*

**Comment by cinnamoner** [comment]
I'm pretty much done. I'm still contemplating it for a while, then I'll unlock it. Some are probably tracking already ... some others will be @ If you're not interested, then so be it.

**Comment by cinnamoner** [comment]
3,2,1 ... go!

**Comment by cinnamoner** [comment]
@MichaelTunnell 
@NikoKrause
@bluedxca93 
Have a look. The others can track it.

**Comment by cinnamoner** [comment]
Anyone is welcome.

**Comment by cinnamoner** [comment]
A community experiment in progress ...

**Comment by cinnamoner** [comment]
The three guys (unknown to me) who are tracking (man, am I that interesting to you? why?) are welcome to participate as well.

**Comment by MichaelTunnell** [comment]
> I'm not an open-source purist but I pretty much like what Richard Stallman preaches. It should be that way but for now, at least some of it, remains a desiderata. With that being said, I'm addressing a question. It goes like this: Which app would he use?
>
>a) Telegram
>b) Wire

RMS would not use either service.

1. RMS is an advocate of Free Software not Open Source. There is overlapping between the two but they are different things.
2. Neither Telegram nor Wire are Free Software and in fact, neither are truly Open Source. The server software for both services is proprietary.

-----

In terms of community chatting I think both Telegram and Wire have equal amount of pros and cons. The biggest problem with Telegram Groups is a lack of real control. Wire's biggest problem is having to get people to use yet another chat service.

-----

Overall, I would suggest people consider Matrix+Riot.

Someone could make a room on Matrix.org and everyone could communicate in it via Riot.im - people could then also setup an IRC channel on Freenode to integrate the two so people who want a Wire/Slack style client can use Riot and the people who want IRC style can use their favorite IRC client.

This is the best solution in my opinion for public chat for a project.

------

in Antergos, we use IRC<->Matrix+Riot<->Telegram integration but the Telegram part of it is a bit problematic. IRC<->Matrix+Riot is great.

**Comment by cinnamoner** [comment]
@MichaelTunnell Thank you Michael. I'm considering my alternatives, you know. Cause, as you pointed a number of times, Git ain't a chat service, agreed.

**Comment by MichaelTunnell** [comment]
> Thank you Michael.

Welcome. 

> I'm considering my alternatives.

Telegram makes the most sense for basic conversations with individuals and in some cases a small group as well. It starts to show its flaws when you reach a certain size group. 30+ is usually where it starts to become clunky, 50+ it gets problematic and 100+ is where it becomes kind of messy.

For **most communication I would suggest Telegram** over Wire because it's really a dominant force in the world of competition to Facebook Messenger.

-------

However, in the terms of a **_community project public chat room_**. I think **IRC<->Matrix/Riot** is the best option because it covers the hardcore IRC fans and the non-IRC users all in the same chat.

------

> I'm considering my alternatives, you know. Cause, as you pointed a number of times, Git ain't a chat service, agreed.

Glad to see you are looking elsewhere.

Quick Note: GitHub and Git are not exclusive to each other. Git is version control software. GitHub is a business that uses Git as their service infrastructure.

**Comment by cinnamoner** [comment]
@MichaelTunnell 
I'm also interested in how really Telegram and Wire live up to their claims on one's privacy. One's privacy is sacred. As Rob (Linux Quest - that's where I heard about Telegram for the first time :)) pointed out in one of his videos:

> I've got nothing to hide but it's none of their business

And since we've got so far, what's your take on the much-discussed surveillance society. Do you think the human species is headed towards a Borg-like dystopia? And that would be all :)

**Comment by MichaelTunnell** [comment]
> I'm also interested in how really Telegram and Wire live up to their claims on one's privacy. One's privacy is sacred. 

Telegram and Wire are both proprietary servers so you are really just taking their word for it that they don't have decryption on it.

Wire claims everything is encrypted where as Telegram has "Secret Chats" where only those are encrypted.

>> I've got nothing to hide but it's none of their business

I agree with that.

> what's your take on the much-discussed surveillance society.

Not a fan.

> Do you think the human species is headed towards a Borg-like dystopia? 

Doubtful because while most people don't seem to care, enough of us do care enough for it to not go that far. :)

**Comment by cinnamoner** [comment]
@MichaelTunnell Thank you very much.

**Comment by teller** [comment]
Hi, jumping in from the Wire team here.

> Telegram and Wire are both proprietary servers so you are really just taking their word for it that they don't have decryption on it.

E2EE means you don't need to trust the server, messages are encrypted on one end and decrypted on the other. Keys never leave the devices.

We've also publicly announced that server will be open sourced by the end of Q1 this year.

Some other resources to verify Wire claims:

Security whitepaper:
https://wire.com/resource/Wire%20Security%20Whitepaper/download/
Privacy whitepaper:
https://wire.com/resource/Wire%20Privacy%20Whitepaper/download/
Independent review: 
https://www.x41-dsec.de/reports/Kudelski-X41-Wire-Report-phase1-20170208.pdf

**Comment by MichaelTunnell** [comment]
@teller 

> E2EE means you don't need to trust the server, messages are encrypted on one end and decrypted on the other. Keys never leave the devices.

How does it handle the syncing of data? Does one account share the same keys over all devices? This is where Signal always seemed to have an issue.

> We've also publicly announced that server will be open sourced by the end of Q1 this year.

I have not seen that announcement. That would be fantastic.

My only hesitation for using Wire was always the fear of vendor lock-in not whether I want to self-host or not. I merely want the ability to self-host if needed but would prefer not to.

Has a license been designed on for the source release?

**Comment by teller** [comment]
> Syncing

Each device has unique key. 

> Announcement

Was at the end of the post where we announced the security audit: https://medium.com/wire-news/wires-independent-security-review-61f37a1762a8#.atglv5u3i

> Licence

Nothing I can share yet. Soon.

**Comment by cinnamoner** [comment]
@teller As a host, I feel the urge to say *thank you* for jumping in.

**Comment by cinnamoner** [comment]
My intention is to keep this thread streamlined. But I do wonder about this project/service as well.
https://github.com/BelledonneCommunications/linphone
http://linphone.org/technical-corner/linphone/downloads

**Comment by cinnamoner** [comment]
@MichaelTunnell My intention is to tag you as little as possible due to obvious reasons. On the other hand, given the more or less dynamic nature of the thread, please jump in once in a while just to keep updated. Thanks.

**Comment by cinnamoner** [comment]
I'm also addressing a heartfelt welcome to @Quidsup, should he be interested in participating.

**Comment by cinnamoner** [comment]
I'm leaning towards Wire at the moment.

**Comment by MichaelTunnell** [comment]
@teller 

> Each device has unique key. Content sent n times depending on number of devices for both the sender and receiver.

I see, so the messages are sent multiple times in order to go to all devices that need to be sync'd. I like that approach.

> Was at the end of the post where we announced the security audit: https://medium.com/wire-news/wires-independent-security-review-61f37a1762a8#.atglv5u3i

Thanks for the information . . . going to share that info on Reddit. :)

>> License
> Nothing I can share yet. Soon.

Understandable.

**Comment by cinnamoner** [comment]
> Nothing to share yet. Soon.

The license is a key factor.

**Comment by MichaelTunnell** [comment]
> Anything without a hashtag makes me fell uneasy. Could it be addressed? SHA256 should suffice. Yeah a hashtag for the binaries.

hmm that is interesting they have a hash for Android & Windows but not for Linux binaries . . . interesting.

@cinnamoner those are not "hashtags".

You are referring to cryptographic hashes.

Hashtag comes from Twitter with something like #opensource. The # symbol is known as a "hash" and combine that with a keyword/tag = hashtag.

**Comment by cinnamoner** [comment]
@MichaelTunnell Hold on, I've just overstepped my own rule. Yeah, checksum. Hold on.

**Comment by cinnamoner** [comment]
SHA256:	 e98988869f9db79b754a76e3d0fe18e5b430b7d7d26a055cfd62daa91a18ac82
File name:	wire_2.11.2722_amd64.deb

This is an unedited post. This is the correct way of posting a checksum. Everything has been done on the same device. Hence, it's inconclusive. One should use a double/triple blind method (depending on one's degree of paranoia :)

**Comment by cinnamoner** [comment]
@MichaelTunnell Some corrections upstream.

**Comment by cinnamoner** [comment]
So, if puzzled, it goes like that: say someone has someone else's credentials and edits the sum. It will read *edited*. But say someone with someone else's credentials delelets the post, then posts a new post to replace the initial post. It will most likely show. If for no other reason the timestamp of the new post will be different. But of course, all that doesn't matter, does it? :)

**Comment by cinnamoner** [comment]
@MichaelTunnell Have you checked the business model? Why would Iconical be so generous to finance Wire?

**Comment by cinnamoner** [comment]
> hmm that is interesting they have a hash for Android & Windows but not for Linux binaries . . . interesting.

@MichaelTunnell They upversioned recently. It's probably comming.

**Comment by cinnamoner** [comment]
@teller 

1. Who/what is Iconical as an entity?
2. What motivates Iconical to finance Wire?
3. I like your proactiveness. Just curious how did you find us so quickly?

@MichaelTunnell Just posted some question. Stay tunned, please.

**Comment by cinnamoner** [comment]
@ghismary I wonder whether you would like to participate as well. Thank you.

**Comment by cinnamoner** [comment]
Note: *the thread has just been overhauled just enough to be more streamlined and easier to read. For now, the outcome of the present endeavour is inconclusive but I'm confident.*

**Comment by cinnamoner** [comment]
@MichaelTunnell Anything you wanna share?

**Comment by MichaelTunnell** [comment]
> Whenever the word "telegram" is spelled on GitHub, Telegram know about it, righ? I'm wondering why haven't they jumped in as well.

I have no idea if they do that or not but I most certainly wouldn't do that. That is a massive amount of work and potential noise to aggregate and filter, I wouldn't bother. If someone wants to contact me about a project then I provide ways to do that and if people don't use those methods then it's not up to me to try find it and it's unreasonable for anyone to expect me to do that.

>Whenever the word "wire" is spelled on GitHub, you know about it, right? It's how you've found us, right?

He could have been actively searching. Do not assume you know how others do things because you are almost always guaranteed to be wrong.

> What motivates Iconical to finance Wire?

they are going to offer premium services by the end of 2017

**Comment by cinnamoner** [comment]
> Do not assume you know how others do things because you are almost always guaranteed to be wrong.

@MichaelTunnell I've just quoted myself :)  

I think the thread has served its purpose. Hence, I'm closing it.

I'm addressing a *thank you* to the participants.

**Comment by cinnamoner** [comment]
PS: @MichaelTunnell Whenever the word "wire" is spelled on GiHub, Wire knows about it:)

**Comment by teller** [comment]
Sorry guys, still want to respond to couple of the questions:

• Linux checksum - Something we need to fix. No particular reason not to have it for Linux.

• Iconical is a venture capital investment company. These companies are typically motivated by increasing returns for investors. Wire is for profit.

> Whenever the word "wire" is spelled on GitHub, you know about it, right? It's how you've found us, right?

No, Github does not work like that. I found it via medium.com that I use to monitor mentions of "wire".

**Comment by MichaelTunnell** [comment]
> Linux checksum - Something we need to fix. No particular reason not to have it for Linux.

Agreed.

> No, Github does not work like that. I found it via medium.com that I use to monitor mentions of "wire".

Mind explaining how to do that?

**Comment by cinnamoner** [comment]
> Wire is for profit. 

@teller Understandable. Mind explaining the mechanism?

@MichaelTunnell I had visited the homepage several times and downloaded packages therefrom. I had not used any means whatsoever to detect/prevent/block tracking. Hadn't even bothered to flush cookies/cache or anything else if present. And definitely hadn't cloaked my identity. Therefore, I had made it as easy as possible for Wire to track me. Oh, and I had run some  common search on the the internet. But I'm still interested in your question addressed to teller. And of course, Wire haven't upset me in any way whosoever, quite the opposite. I'm grateful to them for addressing our questions.

**Comment by teller** [comment]
Mention.com is a web monitoring service, similar to Google alerts. You give it a word/phrase and it tries to find relevant mentions of that on the internet. Fairly straight forward. We don't track visitors/users individually, don't even have Google Analytics on wire.com.

**Comment by cinnamoner** [comment]
@teller Thank you. 👍

**Comment by MichaelTunnell** [comment]
@teller 

> Mention.com is a web monitoring service, similar to Google alerts.

That makes more sense. Your previous comment said "medium.com" rather than "mention.com" so I was confused. :)

---------

@cinnamoner 

> I had visited the homepage several times and downloaded packages therefrom. I had not used any means whatsoever to detect/prevent/block tracking. Therefore, I had made it as easy as possible for Wire to track me. Oh, and I had run some common search on the the internet. 

That is not how website analytics works at all. Even though Google may collect information based on accounts they do not share it with companies at all. They provide anonomized ids that aren't even IP addresses.

In this case, Wire doesn't use Google Analytics so even if Google shared that data, which they don't, Wire wouldn't have it anyway.

You are not being individually tracked by website analytics tools.

------

@cinnamoner 

> Wire is for profit.

Wire has announced they will be launching for-profit premium services for businesses. This is likely to be a competitor with stuff like Slack though that part is just a guess.

**Comment by cinnamoner** [comment]
@MichaelTunnell There are a multitude of trackers out there in all forms and shapes :) But what I've just stated is beyond the scope of the thread.
